/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liracs.view.interfaces;

import Liracs.shared.domain.join.JoinIgIcC;
import Liracs.shared.util.exceptions.PersistenciaException;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import liracs.view.Stub.StubInstrucaoComando;
import liracs.view.util.Capture;
import liracs.view.util.GestorComando;
import liracs.view.util.Gravacao;

/**
 *
 * @author rafael
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private static Long userLoggedID;
    private static int audioSize;
    private boolean aux = true;
    private boolean gravando = false;
    private GestorComando gestorComando;

    private Capture capture;
    
    public TelaPrincipal(Long ID) {

        initComponents();
        
        microfone.setVisible(false);

        TelaPrincipal.userLoggedID = ID;
        TelaInicial obj = new TelaInicial(userLoggedID);
        area.add(obj);
        obj.setVisible(true);
        titulomenu.setText("Início");
//        gambiarra = this.userLoggedID;
        atualizaMic();
        gestorComando = new GestorComando();
        capture = new Capture();
        //marreta
        capture.start();
        capture.stop();
        capture.zeraAis();
    }

    public TelaPrincipal() {
        userLoggedID = (long) 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        FUNDOBRANCO = new javax.swing.JPanel();
        CABECALHO = new javax.swing.JPanel();
        titulomenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        l_config = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        area = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        perfilimagem = new javax.swing.JLabel();
        perfilnome = new javax.swing.JLabel();
        MENU = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        l_listar = new javax.swing.JLabel();
        l_adicionar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        l_conta = new javax.swing.JLabel();
        l_inicio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        microfone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hotkey(evt);
            }
        });

        FUNDOBRANCO.setBackground(new java.awt.Color(255, 255, 255));
        FUNDOBRANCO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CABECALHO.setBackground(new java.awt.Color(0, 73, 76));
        CABECALHO.setPreferredSize(new java.awt.Dimension(700, 50));
        CABECALHO.setLayout(null);

        titulomenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titulomenu.setForeground(new java.awt.Color(255, 255, 255));
        titulomenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CABECALHO.add(titulomenu);
        titulomenu.setBounds(280, 30, 120, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIRACS");
        CABECALHO.add(jLabel1);
        jLabel1.setBounds(280, 0, 120, 50);

        l_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_settings_white_36dp.png"))); // NOI18N
        l_config.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                config(evt);
            }
        });
        CABECALHO.add(l_config);
        l_config.setBounds(600, 0, 36, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_close_black_16dp.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechar(evt);
            }
        });
        CABECALHO.add(jLabel4);
        jLabel4.setBounds(660, 10, 16, 16);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("-");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizar(evt);
            }
        });
        CABECALHO.add(jLabel7);
        jLabel7.setBounds(650, -1, 10, 30);

        FUNDOBRANCO.add(CABECALHO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        area.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(630, 550));
        jPanel1.setName(""); // NOI18N

        perfilnome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(perfilnome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(perfilimagem)))
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(perfilimagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, Short.MAX_VALUE)
                .addComponent(perfilnome)
                .addGap(119, 119, 119))
        );

        area.add(jPanel1);
        jPanel1.setBounds(-10, 0, 630, 540);

        FUNDOBRANCO.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 630, 540));

        MENU.setBackground(new java.awt.Color(0, 220, 229));
        MENU.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 2, Color.BLACK));
        MENU.setPreferredSize(new java.awt.Dimension(70, 550));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Listar");
        MENU.add(jLabel2);

        l_listar.setForeground(new java.awt.Color(255, 255, 255));
        l_listar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_list_black_48dp.png"))); // NOI18N
        l_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista(evt);
            }
        });

        l_adicionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_add_circle_outline_black_48dp.png"))); // NOI18N
        l_adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Adicionar");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Conta");

        l_conta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_conta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_person_black_48dp.png"))); // NOI18N
        l_conta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conta(evt);
            }
        });

        l_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_home_white_48dp.png"))); // NOI18N
        l_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicio(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Início");

        javax.swing.GroupLayout MENULayout = new javax.swing.GroupLayout(MENU);
        MENU.setLayout(MENULayout);
        MENULayout.setHorizontalGroup(
            MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l_conta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(l_adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(l_listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MENULayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_inicio)
                .addContainerGap())
        );
        MENULayout.setVerticalGroup(
            MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENULayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(l_inicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(54, 54, 54)
                .addComponent(l_listar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addComponent(l_adicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(54, 54, 54)
                .addComponent(l_conta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        FUNDOBRANCO.add(MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 590));

        microfone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/mic_black.png"))); // NOI18N
        microfone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                falar(evt);
            }
        });
        FUNDOBRANCO.add(microfone, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, -1, -1));

        jLayeredPane1.add(FUNDOBRANCO);
        FUNDOBRANCO.setBounds(0, 0, 700, 640);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 640));

        setSize(new java.awt.Dimension(681, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void original() {
        l_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_home_white_48dp.png")));
        l_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_settings_white_36dp.png")));
        l_listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_list_black_48dp.png"))); // NOI18N
        l_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_add_circle_outline_black_48dp.png"))); // NOI18N
        l_conta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_person_black_48dp.png"))); // NOI18N
    }
    private void config(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_config
        // TODO add your handling code here:
        TelaConfigurar obj = new TelaConfigurar();
        area.add(obj);
        obj.setVisible(true);
        titulomenu.setText("Configurações");
        l_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_home_black_48dp.png")));
        l_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_settings_black_36dp.png")));
        l_listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_list_black_48dp.png"))); // NOI18N
        l_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_add_circle_outline_black_48dp.png"))); // NOI18N
        l_conta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_person_black_48dp.png"))); // NOI18N

    }//GEN-LAST:event_config

    private void add(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add
        TelaAdicionar obj = new TelaAdicionar(userLoggedID);
        area.add(obj);
        obj.setVisible(true);
        titulomenu.setText("Adicionar Comando");
        //.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/ic_person_black_48dp.png")));
        l_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_home_black_48dp.png")));
        l_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_settings_white_36dp.png")));
        l_listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_list_black_48dp.png"))); // NOI18N
        l_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_add_circle_outline_white_48dp.png"))); // NOI18N
        l_conta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_person_black_48dp.png"))); // NOI18N
    }//GEN-LAST:event_add

    private void conta(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conta
        TelaConta obj = new TelaConta(userLoggedID);
        area.add(obj);
        obj.setVisible(true);
        titulomenu.setText("Configurar Conta");
        l_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_home_black_48dp.png")));
        l_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_settings_white_36dp.png")));
        l_listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_list_black_48dp.png"))); // NOI18N
        l_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_add_circle_outline_black_48dp.png"))); // NOI18N
        l_conta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_person_white_48dp.png"))); // NOI18N
    }//GEN-LAST:event_conta

    private void lista(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista
        TelaListar obj = new TelaListar(userLoggedID);
        area.add(obj);
        obj.setVisible(true);
        titulomenu.setText("Lista de comandos");
        l_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_home_black_48dp.png")));
        l_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_settings_white_36dp.png")));
        l_listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_list_white_48dp.png"))); // NOI18N
        l_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_add_circle_outline_black_48dp.png"))); // NOI18N
        l_conta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_person_black_48dp.png"))); // NOI18N
    }//GEN-LAST:event_lista

    private void fechar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechar
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_fechar

    private void minimizar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizar
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizar

    private void inicio(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicio
        // TODO add your handling code here:
        TelaInicial obj = new TelaInicial(userLoggedID);
        area.add(obj);
        obj.setVisible(true);
        titulomenu.setText("Início");
        original();
    }//GEN-LAST:event_inicio

    private void hotkey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hotkey
       
    }//GEN-LAST:event_hotkey

    private void falar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_falar
        // TODO add your handling code here:
        
        
        if(!gravando){
            gravando = true;
            microfone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/mic.png")));
        
            capture.start();
            //gravar.go();
        }
        else{
            microfone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/mic_black.png")));
            capture.stop();
            gravando = false;
            Gravacao gravar = new Gravacao(userLoggedID, capture, gestorComando);
            gravar.compare();
        }
    }//GEN-LAST:event_falar
    private static void ed(Long id, JoinIgIcC join) {
        TelaEditar obj = new TelaEditar(id, join);
        area.add(obj);
        obj.setVisible(true);
    }

    private static void mic() {
        StubInstrucaoComando stubInstrucaoComando = new StubInstrucaoComando();
        try {
            audioSize = stubInstrucaoComando.listarPorUsuario(userLoggedID).size();
            if(audioSize >=1){
                microfone.setVisible(true);
            }
//        l_hotkey.setText("Aperte a tecla " + hotkey + " para gravar");
        } catch (PersistenciaException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /*private void dadosUsuario() throws IOException {
     try{
     StubUsuario Suser = new StubUsuario();
     Usuario user = new Usuario();
     user = Suser.consultarPorId(userLoggedID);
     if(user.getEndFoto()!=null){
     //Usuario usuario = new Usuario();
     byte[] b = user.getB();
     File tt = new File("src"+File.separator+"liracs"+File.separator+"view"+File.separator+"icones"+File.separator+"perfil.png");
     FileOutputStream fos = new FileOutputStream(tt);
     fos.write(b);
     fos.close();
     // ImageIcon u = new ImageIcon("src"+File.separator+"liracs"+File.separator+"view"+File.separator+"icones"+File.separator+"perfil.png");
     //System.out.println(b);
     Image caminho = new javax.swing.ImageIcon(tt.getAbsolutePath()).getImage();
     Image img = caminho.getScaledInstance(400, 400, Image.SCALE_SMOOTH);
            
     ImageIcon x = new javax.swing.ImageIcon(img);
     //System.out.println("aquiiiiiiiiiiiii"+perfilimagem.toString());
     perfilimagem.setIcon(x);
     perfilnome.setText(user.getNom_Usuario());
     //perfilimagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("liracs"+File.separator+"view"+File.separator+"icones"+File.separator+"perfil.png")));
     }
     }catch (PersistenciaException ex) {
     Logger.getLogger(TelaCadastrar.class.getName()).log(Level.SEVERE, null, ex);
     }
     }*/

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CABECALHO;
    private javax.swing.JPanel FUNDOBRANCO;
    private javax.swing.JPanel MENU;
    static javax.swing.JDesktopPane area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_adicionar;
    private javax.swing.JLabel l_config;
    private javax.swing.JLabel l_conta;
    private javax.swing.JLabel l_inicio;
    private javax.swing.JLabel l_listar;
    private static javax.swing.JLabel microfone;
    private javax.swing.JLabel perfilimagem;
    private javax.swing.JLabel perfilnome;
    private javax.swing.JLabel titulomenu;
    // End of variables declaration//GEN-END:variables

    public static void edita(Long userLoggedID, JoinIgIcC join) {
        ed(userLoggedID, join);
    }

    public static void atualizaMic() {
        mic();
    }

}
