/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liracs.view.interfaces;

import Liracs.shared.domain.join.JoinIgIcC;
import Liracs.shared.model.domain.InstrucaoComando;
import Liracs.shared.model.domain.Usuario;
import Liracs.shared.util.exceptions.PersistenciaException;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import liracs.view.Stub.StubInstrucaoComando;

/**
 *
 * @author user
 */
public class TelaListar extends javax.swing.JInternalFrame {
    private final long userLoggedID;
    
    public TelaListar(long userLoggedID) {
        this.userLoggedID = userLoggedID;
        initComponents();
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        Insere();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        listagem = new javax.swing.JDesktopPane();

        jLabel1.setText("jLabel1");

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setResizable(true);
        getContentPane().setLayout(null);

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane2.setMinimumSize(new java.awt.Dimension(620, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 550));

        jPanel2.setBackground(new java.awt.Color(0, 146, 152));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(null);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(70, 370, 85, 23);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(160, 370, 82, 23);

        listagem.setMinimumSize(new java.awt.Dimension(345, 280));
        listagem.setPreferredSize(new java.awt.Dimension(345, 280));

        javax.swing.GroupLayout listagemLayout = new javax.swing.GroupLayout(listagem);
        listagem.setLayout(listagemLayout);
        listagemLayout.setHorizontalGroup(
            listagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        listagemLayout.setVerticalGroup(
            listagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel2.add(listagem);
        listagem.setBounds(-11, 75, 340, 280);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 550);

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(0, 0, 620, 550);

        setSize(new java.awt.Dimension(630, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JDesktopPane listagem;
    // End of variables declaration//GEN-END:variables

    private void Insere() {
        StubInstrucaoComando stub = new StubInstrucaoComando();
        Usuario user = new Usuario();
        try{
        //int i = stub.listarPorUsuario(userLoggedID).size();
        List<JoinIgIcC> list = stub.listarPorUsuario(userLoggedID);
        JInternalFrame internalFrame = new JInternalFrame();  
        ((BasicInternalFrameUI)internalFrame.getUI()).setNorthPane(null);
        internalFrame.setBorder(null);
        internalFrame.setSize(335,320);  
        internalFrame.setEnabled(false);
        JPanel  texto = new JPanel();
        JPanel  botoes = new JPanel();
        JPanel  local = new JPanel();
        JPanel  linha = new JPanel();
        linha.setLayout(new GridLayout(0,2));
        local.setSize(315, 305);
        local.setBackground(new java.awt.Color(0,146,152));
        texto.setLayout(new GridLayout(0,1));
        texto.setBackground(new java.awt.Color(255,255,255));
        botoes.setLayout(new GridLayout(0,2));
        botoes.setBackground(new java.awt.Color(255,255,255));
        for(int j = 0; j<list.size();j++){
           JoinIgIcC aux = list.get(j);
           JTextArea t = new JTextArea();
           t.setEditable(false);
           t.setLineWrap(true);
           t.setText(aux.getCom_des_Comando());
           texto.add(t);
           editar e = new editar(userLoggedID, aux);
           JButton b = new JButton(e);
           b.setText("editar");
           b.setBackground(new java.awt.Color(0,73,76));
           botoes.add(b);
           JButton ed = new JButton(e);
           ed.setText("X");
           ed.setBackground(new java.awt.Color(0,73,76));
           botoes.add(ed);
           linha.add(texto);
           linha.add(botoes);
           local.add(linha);
        } 
        
        internalFrame.add(local);
        listagem.add(internalFrame);
        internalFrame.setVisible(true); 
        } catch (PersistenciaException ex) {
         Logger.getLogger(TelaListar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private class editar extends AbstractAction    
        {    
            private JoinIgIcC join;
            private final long userLoggedID;  
            private int numero;    
            
            public editar(Long id, JoinIgIcC join) {    
                   this.userLoggedID = id;
                   this.join = join;
            }    
        
            @Override    
            public void actionPerformed(ActionEvent e) {
                // TODO Auto-generated catch block
                    //TelaEditar obj = new TelaEditar(id);
                    TelaPrincipal.edita(userLoggedID, join);
                    
                ;    
            }    

        }
}
